// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     // ignore: missing_enum_constant_in_switch
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//     }

//     throw UnsupportedError(
//       'DefaultFirebaseOptions are not supported for this platform.',
//     );
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAucYeDR8CvxuW-DNVZU7Vl0DQaJp7VQ5Q',
//     appId: '1:982684465531:web:e469dd7afdfbdee32ae5de',
//     messagingSenderId: '982684465531',
//     projectId: 'flutter-web-deploy-2b520',
//     authDomain: 'flutter-web-deploy-2b520.firebaseapp.com',
//     storageBucket: 'flutter-web-deploy-2b520.appspot.com',
//     measurementId: 'G-3Y4C7SFFCR',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyA-RnHko1RghaS9qUR0RCKAGX1lWh9xCow',
//     appId: '1:982684465531:android:031f933d77efd2ee2ae5de',
//     messagingSenderId: '982684465531',
//     projectId: 'flutter-web-deploy-2b520',
//     storageBucket: 'flutter-web-deploy-2b520.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDiDBmG8Sqw1AyJV8NiLlK9D9tkTY_jD4c',
//     appId: '1:982684465531:ios:55d142a9146f7fa82ae5de',
//     messagingSenderId: '982684465531',
//     projectId: 'flutter-web-deploy-2b520',
//     storageBucket: 'flutter-web-deploy-2b520.appspot.com',
//     iosClientId:
//         '982684465531-v27sjtnrbr3ima4hh5issmss98smmknf.apps.googleusercontent.com',
//     iosBundleId: 'com.example.verygoodcore.web-app',
//   );
// }
